on: push
jobs:
  codesign:
    runs-on: ubuntu-latest
    steps:
        - name: download codesigntool and dependencies
          run: |
            sudo apt-get update && sudo apt-get install -y default-jre-headless
            curl -o codesign.zip https://www.ssl.com/download/codesigntool-for-linux-and-macos/
            unzip codesign.zip
            find .
            chmod +x ./CodeSignTool-v1.2.5/CodeSignTool.sh
            ./CodeSignTool-v1.2.5/CodeSignTool.sh --help
