on: push
jobs:
  codesign:
    runs-on: ubuntu-latest
    steps:
        - name: download codesigntool and dependencies
          run: |
            curl -o codesign.zip https://www.ssl.com/download/codesigntool-for-linux-and-macos/
            unzip codesign.zip
            find .
