on: push
jobs:
  codesign:
    runs-on: ubuntu-latest
    steps:
        - name: download codesigntool and dependencies
          run: |
            curl -o codesign.zip https://www.ssl.com/download/codesigntool-for-linux-and-macos/
            unzip codesign.zip
            find .
            cd ./CodeSignTool-v1.2.5/
            echo -e "#!/bin/bash\n" >> cst.sh
            cat CodeSignTool.sh >> cst.sh
            chmod +x ./cst.sh
            # fix a bug in the script that tries to respect this variable only if it is not set.
            sed -ie 's@if \[\[ -z "${CODE_SIGN_TOOL_PATH}" \]\]; then@if \[\[ -n "${CODE_SIGN_TOOL_PATH}" \]\]; then@' cst.sh
            # trick the script into executing correctly
            echo "CODE_SIGN_TOOL_PATH=$PWD" >> $GITHUB_ENV
            echo "$PWD" >> $GITHUB_PATH
        - name: run codesigntool
          run: |
            cst.sh sign --help
